-- This file is automagically generated.
-- Please visit http://www.wowace.com/projects/bazooka/localization/
-- if you wish to help with the translation.

local L = LibStub("AceLocale-3.0"):NewLocale("Bazooka_Options", "deDE")
if not L then return end

L["Adjust frames"] = "Frames anpassen"
L["Apply"] = "Übernehmen"
L["Apply selected options to selected bars?"] = "Die gewählten Optionen für die ausgewählten Leisten übernehmen?"
L["Apply selected options to selected plugins?"] = "Die gewählten Optionen für die ausgewählten Plugins übernehmen?"
L["Attach point"] = "Ankerpunkt" -- Needs review
L["Auto apply"] = "Autom. Übernehmen"
L["Background"] = "Hintergrund"
L["Background color"] = "Hintergrundfarbe"
L["Background settings"] = "Hintergrund-Einstellungen"
L["Background texture"] = "Hintergrundtextur"
L["Background tile size"] = "Hintergrundflächengröße"
L["Bar"] = "Leiste"
L["Bars"] = "Leisten"
L["Border color"] = "Farbe des Rands"
L["Border texture"] = "Textur des Rands"
L["Border thickness"] = "Dicke des Randes"
L["Bottom"] = "Unten"
L["Clear"] = "Löschen"
L["Create new bar"] = "Neue Leiste erstellen"
L["Disable mouse in combat"] = "Maus im Kampf deaktivieren"
L["Disable mouse out of combat"] = "Maus außerhalb des Kampfes deaktivieren"
L["Disable tooltip"] = "Tooltip deaktivieren"
L["Disable tooltip in combat"] = "Tooltip im Kampf deaktivieren"
L["Enable background"] = "Hintergrund aktivieren"
L["Enabled"] = "Aktiviert"
L["Enable highlight"] = "Hervorhebung aktivieren"
L["Enable simple tooltips"] = "Einfache Tooltips aktivieren"
L["Fade in combat"] = "Im Kampf ausblenden"
L["Fade-in duration"] = "Aufblenddauer"
L["Fade-out delay"] = "Verzögerung beim Ausblenden"
L["Fade-out duration"] = "Dauer des Ausblendens"
L["Fade out of combat"] = "Außerhalb des Kampfes ausblenden"
L["Font"] = "Schrift"
L["Font outline"] = "Schriftkontur"
L["Font size"] = "Schriftgröße"
L["Force Hide Tooltip"] = "Tooltip ausblenden erzwingen"
L["Height"] = "Höhe"
L["Hide tooltip on click"] = "Tooltip bei Klick verstecken"
L["High"] = "Hoch"
L["Icon size"] = "Symbolgröße"
L["Left"] = "Links"
L["Left margin"] = "linke Begrenzung"
L["Locked"] = "Gesperrt"
L["Low"] = "Niedrig"
L["Medium"] = "Mittel"
L["Normal"] = "Normal"
L["Opacity"] = "Transparenz"
L["Plugin display settings"] = "Plugin-Anzeige-Einstellungen"
L["Plugins"] = "Plugins"
L["Remove bar"] = "Leiste entfernen"
L["Remove %s?"] = "%s entfernen?"
L["Right"] = "Rechts"
L["Right margin"] = "rechte Begrenzung"
L["Select All"] = "Alle auswählen"
L["Selection"] = "Auswahl"
L["Settings"] = "Einstellungen"
L["Show icon"] = "Symbol anzeigen"
L["Show label"] = "Bezeichnung anzeigen" -- Needs review
L["Show text"] = "Text anzeigen"
L["Show title"] = "Titel anzeigen"
L["Strata"] = "Strata"
L["Text color"] = "Textfarbe"
L["Thick"] = "Dick"
L["Top"] = "Oben"
L["Width"] = "Breite"

